### PR TITLE
tracs part for simulating TCT of PIN merged into raser

### PR DESCRIPTION
**Pull request by Zombatar**
Dear all,
    TRACS's part for simulating the TCT of PIN has been merged into RASER. I moved some the header files need to ./include and the environment is described in the Dockerfile. For now, I just moved some classes and the menber functions needed for simulating TCT of PIN and did not do more works on the code into the functions, so I can not guarantee this is the shortest version, maybe, but it is good to give the results.
    And next step, we need to update fenics and boost? or just fix the LGAD part and get the result for LGAD first?

Best regard,
Jianing

### CODE REVIEW

**Comment by xshi** [comment]
I'm afraid that there are too many files to be included for this commit. 

Could @tanyh2018 and @rkiuchi  take a look and see if it's possible to minimize? 

Thanks!

**Comment by Zombatar** [comment]
remove local boost header files

**Comment by Zombatar** [comment]
we need to update fenics? or just fix the LGAD part and get results for LGAD first?

**Comment by xshi** [comment]
Close and will keep python only development.

**Pull request closed without merging**
