### PR TITLE
0.4.2 TPA-TCT scan created

### PR DESCRIPTION
**Pull request by heheda2001123**
同时增加了针对top和edge-TCT的开关（未完成）

### CODE REVIEW

**Comment by tanyh2018** [comment]
Please add your content based on the latest version of raser on GitHub. Minimize changes as much as possible.

**Comment by heheda2001123** [comment]
针对主干中最新版做了调整。

**Comment by tanyh2018** [comment]
Due to the changed contents include TCT, I don't know whether the merge is OK? @xshi

**Comment by heheda2001123** [comment]
Adjusted to minimize changes. Now most codes of 0.4.1 are independent (despite repetition)

**Pull request closed without merging**
